### ISSUE TITLE
Adjust 'dislike' presentation

### ISSUE THREAD

**Issue by rssmith33** [laureate-institute-for-brain-research/StimToolOnline#14]
We decided the negatives with the dislike symbols was too confusing. So we decided the dislikes will just be shown as positive numbers and that there will be a separate "social rejection score" that changes with each time they make a choice (still at the top right of the screen like before), but it will start over with each new chatroom.

**Comment by rssmith33** [comment]
Actually, Claire and I came up with something better. She will describe it to you in detail tomorrow. But we figured out in the like rooms we can start their social approval at 0% and slowly build it up, and in the dislike rooms we can start their social approval at 100% and have it slowly drop with each choice.

**Comment by LavalleyCA** [comment]
No more social disapproval anywhere. After each chatroom, he *does* want it to display the final score but only "Social Approval Score", regardless of which room they were in. In the "like" rooms, the Social Approval Score (which is back on the right sidebar) will begin at 0% (0/100 or 0/600) and build up as they gain likes (60/600 displays 10%, 120/600 displays 20%, etc). In the "dislike" rooms, the Social Approval Score will begin at 100% (100/100 or 600/600) and decrease as participants gain dislikes (eg. 60 dislikes will display 90% because they now have 540/600 likes, 120 dislikes will show 80%, etc).

**Comment by rssmith33** [comment]
Yes, and social approval score should still be at the top and large as in the last iteration.

Best,

Ryan
________________________________

**Comment by toujames** [comment]
Update the changes for this issue.
It's in production.
