### ISSUE TITLE
emotion faces task - text above images

### ISSUE THREAD

**Issue by rssmith33** [laureate-institute-for-brain-research/StimToolOnline#43]
For some reason, there is small white text above and to the left of each image when they're shown during the actual task (but not during the initial untimed part). This text needs to be removed.

**Comment by toujames** [comment]
Those white texts are actually embedded in the images you sent.
You just see it in the actual task because the image is centered, whereas the untimed portion, it's sort of cut off.

See an example image:
![MC08_Ang_075_](https://user-images.githubusercontent.com/7041040/189032911-14f56b66-2e66-4878-88d7-fd0f39d34b88.jpg)

**Comment by rssmith33** [comment]
Is there a way you could automatically crop out or block the top little bit of each image to remove the text then?

**Comment by toujames** [comment]
Done. Cropped off 9 pixesl the top of each images using script.

See  **crop_images.bash** in  utilities folder.

Commit 
62599ac

**Comment by rssmith33** [comment]
Is there a way you could automatically crop out or block the top little bit of each image to remove the text then?

Best,

Ryan

Ryan Smith, PhD
Principal Investigator
Laureate Institute for Brain Research

Research Associate Professor
Oxley College of Health Sciences
University of Tulsa, Tulsa Oklahoma
https://www.laureateinstitute.org/ryan-smith.html
________________________________
