### ISSUE TITLE
Emotional Faces Task: update readme

### ISSUE THREAD

**Issue by toujames** [laureate-institute-for-brain-research/StimToolOnline#62]
need readme for emotional faces task

**Comment by Aeoconor** [comment]
I have committed a version of the new readme that I've been holding on to for a while to the dev branch at c0d01df94cae925147077f31d199921a0f0cbaa3. However, I don't think this ticket should be closed yet since I am anticipating that further changes will need to be made to the trial structure section of the readme and since I have not pushed the new readme to main.

**Comment by toujames** [comment]
great. Once you go ahead and think it's good an push it to main. we'll close this ticket

**Comment by Aeoconor** [comment]
At this point, I think the desired structure of the emotional faces task is fully realized and the readme has been updated accordingly. Also, these changes are now on main, so this should be good to close.

Commits:
3e4c71828bf6bb1dd75cfda8454e476678513bf8
fe8701fccafc44c58ee4cdad94dd1bc34c003752
c0d01df94cae925147077f31d199921a0f0cbaa3

**Comment by toujames** [comment]
Great, all looks good. Thanks Aardron.
